Hex View Rework
vgmtrans/vgmtrans pull request #237
Opened 2021-08-18 07:15 UTC by DubiousDoggo

## Description
- QHexDocument reads directly from the VGMFile
- Moved some functionality from QHexDocument and QHexCursor into QHexView 
- Selected events in the tree view are highlighted in the hexview, bold with red outline, and visa versa
- Updated font

## How Has This Been Tested?

- General UI stress testing

## Screenshots:
- Container selection from tree view
![image](https://user-images.githubusercontent.com/35575261/129853201-1bf630da-e62c-48ed-8565-ecafb0a25f71.png)

- Multi line selection
![image](https://user-images.githubusercontent.com/35575261/129853905-66cee63a-4ad1-4479-8361-97bbcbaa3d11.png)

- Contiguous Area
![image](https://user-images.githubusercontent.com/35575261/129854124-c1e95efe-cd52-44d6-9322-6c79d076d142.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. 
- [x] I have read the **CONTRIBUTING** document.

2021-08-18 11:04 UTC, sykhro requested changes
Looks very good overall, please remember to squash the fixup commits.

2021-08-18 23:58 UTC, DubiousDoggo commented on src/ui/qt/workarea/VGMFileTreeView.h
> +  auto getTreeWidgetItem(VGMItem *vgm_item) { return m_items.at(vgm_item); };
Assuming everything else is working correctly, the only way I can see it failing is if a null pointer gets passed somehow. Any exception should get caught by Qt and display a message, so at least then if it does fail it'll be a lot easier to debug.

2021-08-19 08:01 UTC, sykhro reviewed
The changes are fine but they should be squashed onto their original commits (commit message says "remove dead code" but actually does a whole lot more).

2021-08-22 09:45 UTC, sykhro commented on src/ui/qt/workarea/VGMFileTreeView.h
> +  auto getTreeWidgetItem(VGMItem *vgm_item) { return m_items.at(vgm_item); };
That's fine for me, if that ever throws then it means there's a bug

2021-08-22 09:46 UTC, merged