Fix overflow in VAB
vgmtrans/vgmtrans pull request #283
Opened 2022-01-22 09:04 UTC by Meerkov

Technically this can overflow. I'm not sure if it has practical effects, but this fixes it.

I tested it, and the file I tried gave the same output as before. But for some other inputs it might be different.

2022-01-22 22:47 UTC, Meerkov commented
Please take a look. When the number of instruments was 1, the code would parse first the 0 offset, then the 1 offset. But instrument 1 doesn't exist.

This probably wouldn't cause too many problems, but if there was 512 instruments used, this would seemingly start doing some wacky things.

2022-01-26 22:11 UTC, loveemu requested changes
Thank you for your contribution! The original code was strange and confusing to me, and I think your changes are reasonable. I made a few suggestions, albeit trivial ones.

2022-01-26 22:27 UTC, Meerkov commented on src/main/formats/Vab.cpp
> +  AddVolume(((long)GetByte(dwOffset + 2) * (long)instr->masterVol) / (127.0 * 127.0), dwOffset + 2, 1);
Sounds good. I just figured I'd remove the warning that Visual Studio shows here. I changed it to the format you suggest.

2022-01-26 22:31 UTC, Meerkov commented on src/main/formats/Vab.cpp
>        }
Agreed.

2022-01-26 22:31 UTC, Meerkov commented on src/main/formats/Vab.cpp
> +      vagSize = GetShort(offVAGOffsets + i * 2) * 8;
Looks good

2022-01-26 22:32 UTC, Meerkov commented on src/main/formats/Vab.cpp
>          vagLocations.push_back(SizeOffsetPair(vagOffset, vagSize));
No reason not to. Should be nearly identical.

2022-01-27 01:10 UTC, loveemu approved these changes

2022-01-27 01:10 UTC, loveemu commented on src/main/formats/Vab.cpp
> +        vagLocations.emplace_back(SizeOffsetPair(vagOffset, vagSize));
It's still a little different from my intention.

```suggestion
        vagLocations.emplace_back(vagOffset, vagSize);
```

 I should have used a suggestion style comment, but I was unfamiliar with reviews and overlooked them.

2022-01-27 01:10 UTC, loveemu commented on src/main/formats/Vab.cpp
> +  AddVolume(long{(GetByte(dwOffset + 2) * instr->masterVol)} / (127.0 * 127.0), dwOffset + 2, 1);
I have compiled Vab.cpp in Visual Studio 2022 with the warning level set to maximum, but no warning appears on this line. In my opinion, this code may not overflow even in its original form.

```suggestion
  AddVolume((GetByte(dwOffset + 2) * instr->masterVol) / (127.0 * 127.0), dwOffset + 2, 1);
```

2022-01-27 01:12 UTC, loveemu commented on src/main/formats/Vab.cpp
>          vagLocations.push_back(SizeOffsetPair(vagOffset, vagSize));
Commented in my next review.

2022-01-27 01:13 UTC, loveemu commented on src/main/formats/Vab.cpp
> +  AddVolume(((long)GetByte(dwOffset + 2) * (long)instr->masterVol) / (127.0 * 127.0), dwOffset + 2, 1);
I commented on this in my next review. I don't think the original code caused any overflow or unintended downsize casts.

2022-01-27 01:21 UTC, Meerkov commented on src/main/formats/Vab.cpp
> +        vagLocations.emplace_back(SizeOffsetPair(vagOffset, vagSize));
This also draws my attention to the fact that this pair is badly named. It should be OffsetSizePair because of the ordering of inputs... But I'll follow up with renaming that rather than do it now.

2022-01-27 03:15 UTC, loveemu commented
@sykhro I have approved the pull request. There are several merge strategies to choose from, do you have any recommendations?

2022-01-27 09:13 UTC, sykhro commented
I'm okay with anything but squashing. Perhaps we can go for rebase & merge, up to you. Whatever we end up choosing it should probably become the default from now on

2022-01-27 10:16 UTC, merged