Command Line Interface
vgmtrans/vgmtrans pull request #340
Opened 2023-02-12 05:34 UTC by jeremander

## Description

This implements a rudimentary command line interface (CLI) for `vgmtrans`.

## Motivation and Context

A command line interface makes it easier to run `vgmtrans` in scripts, and to convert files in bulk.

See vgmtrans#297 for the original enhancement proposal.

## How Has This Been Tested?

- Tested the new CLI program on a handful of SPC and PSF files on Mac OS 13.1 and Linux Ubuntu 20.04, successfully exporting them to MIDI/SF2/DLC.
- **Not yet tested on Windows.**

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- Changes largely do not affect core code or GUI applications.
- The name of the CLI executable is `vgmtrans` (lowercase).  On Linux this conflicted with the name of the GUI, so I changed the latter name to `vgmtrans-gui`.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

2023-02-12 09:58 UTC, sykhro requested changes
Hello, thank you for your contribution! I have left a few comments

2023-02-12 09:58 UTC, sykhro commented on src/main/Matcher.cpp
> +  if (instrsets.size() >= 1 && sampcolls.size() >= 1) {
Why was this necessary? I can see this breaking a lot of formats

2023-02-12 09:58 UTC, sykhro commented on src/main/pch.h
> +#include <filesystem>
Should drop this to avoid the compilation failures that made using GHC filesystem necessary

2023-02-12 09:58 UTC, sykhro commented on src/ui/qt/CMakeLists.txt
> +  set_target_properties(vgmtrans PROPERTIES OUTPUT_NAME vgmtrans-gui)
This breaks a lot of stuff in packaging releases. Please keep the GUI version as `vgmtrans`.

2023-02-12 09:58 UTC, sykhro commented on src/ui/cli/CMakeLists.txt
> +        OUTPUT_NAME vgmtrans)
See note below about naming of the executable.

2023-02-12 16:26 UTC, jeremander commented on src/ui/qt/CMakeLists.txt
> +  set_target_properties(vgmtrans PROPERTIES OUTPUT_NAME vgmtrans-gui)
The thought here was that it might trip someone up to have both two command-line programs with similar names, one a CLI and one a GUI.  Cleanest naming scheme would probably be `vgmtrans-cli` (CLI) / `vgmtrans-gui` (GUI), but for now we'll stick with `vgmtrans-cli` (CLI) / `vgmtrans` (GUI) to avoid breaking packaging.

2023-02-12 17:33 UTC, jeremander commented on src/main/Matcher.cpp
> +  if (instrsets.size() >= 1 && sampcolls.size() >= 1) {
The logic here seems quite error-prone (admittedly, I don't fully understand it).  For the GUI, this apparently needs to be called every time a file is added in order to maintain a consistent state, but the way it clears the file lists after a new collection is created can lead to some weird bugs.

For the CLI, one bug I observed was the generation of two collections for `file1` when called like:

`vgmtrans-cli file1.psf subdir/file1.psf`

But only two collections (one for `file1`, one for `file2`) when called like:

`vgmtrans-cli file1.psf subdir/file1.psf file2.psf`

Only in some cases did this happen, though.

Updating the line above to `>=` instead of `==` fixed that particular bug.  But I'm not sure what the downstream effect will be on other situations, and it seems difficult to test...

Most likely, fixing all the potential bugs here might entail a major rewrite of the matcher code.

2023-02-13 09:59 UTC, sykhro commented on src/main/Matcher.cpp
> +  if (instrsets.size() >= 1 && sampcolls.size() >= 1) {
> The logic here seems quite error-prone (admittedly, I don't fully understand it)

I honestly don't either, this code is almost as old as I am and nobody has touched these bits in a decade...


> For the CLI, one bug I observed was the generation of two collections for file1 when called like:

Where the collections actually valid music? You might see that yes, the program outputs something, but that something has completely wrong instruments assigned.
PSX formats often don't have enough information/have simple heuristics for sample detection so we often end up detecting garbage as sample collections. This is the reason the "Create new collection" dialog was introduced in the GUI, so that the user can override the `Matcher` code (which, in the case of PlayStation formats, does fail quite often).


> Only in some cases did this happen, though.

Yes, saying that `Matcher` is brittle is an understatement. Unfortunately the whole app relies on global state which is mapped 1:1 with the way the GUI was designed (I have been trying to change this without breaking stuff but it's a long and painful process), there are definitely bugs that pop up with specific files and/or the order they're opened.

If this is a deal-breaker for the CLI, I would add a switch to toggle between this and the current behaviour. Yes, it's awful, but it's the burden of 20 years of code being built around universal assumptions that didn't turn out to be quite true :)

2023-02-14 00:33 UTC, jeremander commented on src/main/Matcher.cpp
> +  if (instrsets.size() >= 1 && sampcolls.size() >= 1) {
Ha, glad I'm not the only one in the dark here.  😂

Yeah, so there was no problem at all with the SPCs, but as you said, things were trickier with the PSFs, probably because multiple sample collections were generated.  For some PSFs I was just getting unplayable garbage out, but sometimes I was getting actual music where the instruments would occasionally be wrong.

It definitely sounds complicated to clean all this up.  I think I will play around with it for a little while longer, and then call it a day and follow the suggestion you gave of just flipping a switch to do things a bit differently in CLI mode.  Ugly, but it should hopefully fix the bug I had without affecting the GUI at all.

2023-02-14 22:41 UTC, jeremander commented on src/main/Matcher.cpp
> +  if (instrsets.size() >= 1 && sampcolls.size() >= 1) {
OK, the latest change reverts the matching logic to how it was in the GUI case, with a global switch set up to change how it works in the CLI case.  Hopefully this suffices for now.

2023-02-19 21:49 UTC, sykhro requested changes
Just a couple small things I had missed

2023-02-19 21:49 UTC, sykhro commented on src/ui/cli/CLIVGMRoot.cpp
> +#include <sys/stat.h>
`#ifndef _WIN32`

2023-02-19 21:49 UTC, sykhro commented on src/ui/cli/CLIVGMRoot.cpp
> +    if (mkdir(outputDir.c_str(), 0770)) {
`fs::create_directory()`

2023-02-19 21:51 UTC, sykhro commented on src/VGMTransConfig.h.in
> +#define VGMTrans_VERSION @VGMTrans_VERSION@
We already have this, see `version.h.in`

2023-02-19 22:35 UTC, jeremander commented on src/VGMTransConfig.h.in
> +#define VGMTrans_VERSION @VGMTrans_VERSION@
Nice, didn't see this earlier.

2023-02-19 22:36 UTC, jeremander commented on src/ui/cli/CLIVGMRoot.cpp
> +#include <sys/stat.h>
Import should now be unnecessary after switch from `mkdir` to `create_directory`?

2023-02-19 22:40 UTC, sykhro commented on src/ui/cli/CLIVGMRoot.cpp
> +#include <sys/stat.h>
Right!

2023-02-19 22:41 UTC, sykhro approved these changes

2023-02-19 22:41 UTC, sykhro commented
Thank you again for your time :), will merge once CI passes as it never ran before on this branch

2023-02-19 22:57 UTC, jeremander commented
Ya no problem!  As I feared, the Windows build might have a few issues... unfortunately I don't have much experience with that.

2023-02-19 23:06 UTC, sykhro commented
> Ya no problem! As I feared, the Windows build might have a few issues... unfortunately I don't have much experience with that.

Looks like there's no implicit conversion from `fs::path` to `std::string` on Windows (`inputFiles` is `set<string>`). Making it a `set<fs::path>` should fix it (even better actually, as the other code seems to treat `inputFiles` contents as paths anyway)

2023-02-20 10:45 UTC, sykhro commented on src/ui/cli/CLIVGMRoot.cpp
> +          baseName = p.second.stem();
`baseName = p.second.stem().string()`

2023-02-20 10:46 UTC, sykhro commented on src/ui/cli/main_cli.cpp
> +  return success ? EXIT_SUCCESS : EXIT_FAILURE;
`#include <stdlib.h>` needed for this

2023-02-22 13:54 UTC, sykhro commented
Great! One last thing: as per our contribution guidelines, fixup commits should be squashed.

2023-02-22 21:57 UTC, jeremander commented
OK, I _think_ that did the trick...

2023-02-22 22:41 UTC, sykhro commented
Thank you for your contribution and your patience! I will add this to the 2nd preview release soon-ish.

2023-02-22 22:41 UTC, merged