Some post-rework build/compile fixes
vgmtrans/vgmtrans pull request #471
Opened 2024-05-06 00:30 UTC by TheComputerGuy96

2024-05-06 00:32 UTC, mikelow commented
Can you state what OS and compiler you had difficulties with?

2024-05-06 00:44 UTC, TheComputerGuy96 commented
> Can you state what OS and compiler you had difficulties with?

I'm using Arch Linux with GCC 13.2.1 :frog:

2024-05-06 01:07 UTC, mikelow commented
What is the issue you are having with the git submodule relative path? That wasn't changed by the refactor merge.

2024-05-06 01:13 UTC, TheComputerGuy96 commented
> What is the issue you are having with the git submodule relative path? That wasn't changed by the refactor merge.

That's an issue I found when trying to configure spdlog submodule (which was added as a dependency in the rework); I'm surprised no one catched it before

2024-05-06 01:17 UTC, mikelow commented
> That's an issue I found when trying to configure spdlog submodule (which was added as a dependency in the rework); I'm surprised no one catched it before

What is the error you are experiencing? And may as well ask, what version of git?

2024-05-06 06:34 UTC, sykhro requested changes

2024-05-06 06:34 UTC, sykhro commented on .gitmodules
What is the issue here? If anything, the real problem can be the spdlog url

2024-05-06 08:52 UTC, TheComputerGuy96 commented
> What is the error you are experiencing? And may as well ask, what version of git?

Here's the error I have with `git submodule update --init` (with git 2.45.0):
```
❯ git submodule update --init
fatal: repository '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' does not exist  
fatal: clone of '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' into submodule path '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/src/vgmtrans/lib/vgmtrans-ext-win' failed  
Failed to clone 'lib/vgmtrans-ext-win'. Retry scheduled  
fatal: repository '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' does not exist  
fatal: clone of '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' into submodule path '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/src/vgmtrans/lib/vgmtrans-ext-win' failed  
Failed to clone 'lib/vgmtrans-ext-win' a second time, aborting  
```

2024-05-06 08:54 UTC, TheComputerGuy96 commented on .gitmodules
I just posted a comment showing the exact issue I have (I think my fix is correct)

2024-05-06 08:58 UTC, sykhro commented
> > What is the error you are experiencing? And may as well ask, what version of git?
> 
> Here's the error I have with `git submodule update --init` (with git 2.45.0):
> 
> ```
> ❯ git submodule update --init
> fatal: repository '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' does not exist  
> fatal: clone of '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' into submodule path '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/src/vgmtrans/lib/vgmtrans-ext-win' failed  
> Failed to clone 'lib/vgmtrans-ext-win'. Retry scheduled  
> fatal: repository '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' does not exist  
> fatal: clone of '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/vgmtrans-ext-win' into submodule path '/mnt/storagebeast/Development/AUR/Published/vgmtrans-git/src/vgmtrans/lib/vgmtrans-ext-win' failed  
> Failed to clone 'lib/vgmtrans-ext-win' a second time, aborting  
> ```

you need `git submodule init` first, so that git can resolve the right absolute url. relative submodule paths ensure that git picks https or ssh depending on what was used to clone the main repository. defaulting to either can break people workflows (especially in case of a private fork)

2024-05-06 10:24 UTC, TheComputerGuy96 commented
> you need `git submodule init` first, so that git can resolve the right absolute url.

I already ran `git submodule init` before and I still have the same issue

2024-05-08 05:46 UTC, TheComputerGuy96 commented
Any updates on the PR? Should I split the submodule change to a separate PR (because it's somehow controversial)?

2024-05-08 06:40 UTC, sykhro commented
sorry, i missed your reply. as previously stated, the https endpoint can break the workflow of people using git with ssh. relative submodule paths are common practice to avoid this problem.

did you fork the repo via github and then clone? in that case you will also need to fork the submodule.
to avoid this issue, clone this repo first and push to your fork remote afterwards

2024-05-08 06:51 UTC, TheComputerGuy96 commented
I dropped the submodule change (apparently my problem is caused by makepkg using two separate .git folders for each repository and the one with all the files using a local URL for the git remote which links to that other one with all the objects) :frog:

2024-05-08 08:30 UTC, sykhro approved these changes

2024-05-08 08:30 UTC, merged

2024-05-08 08:30 UTC, sykhro commented
Thanks for your contribution!