Warning cleanup 2
vgmtrans/vgmtrans pull request #476
Opened 2024-05-10 06:55 UTC by mikelow

More code cleanup, mostly to get rid of warnings.

Changes in SynthFile.h are actually minor - i moved one of the classes because it is used as a member for classes below it and removed an unused constructor or two Only logical change was adding default initial values for some members in constructors.

A lot of changes address "weak warnings." You'll see I've made a number of methods const or static. Let me know if you think any of this is overkill. 

## How Has This Been Tested?
Basic testing. Files are loading and playing as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code cleanup

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

2024-05-10 07:21 UTC, sykhro requested changes
`const`-correctness is never overkill, this was much needed :)

2024-05-10 07:21 UTC, sykhro commented on src/main/conversion/SynthFile.h
> +        fusOptions(0), usPhaseGroup(0), channel(1), tableIndex(0), sampinfo(nullptr), art(nullptr) { }
Since we're here, let's reduce complexity: it's a good idea to move the default values to member initializers. Rationale [here](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c48-prefer-default-member-initializers-to-member-initializers-in-constructors-for-constant-initializers)

2024-05-10 07:21 UTC, sykhro commented on src/main/components/VGMColl.cpp
> +        sampInfo->SetPitchInfo(realUnityKey, realFineTune, attenuation);
Sneaky bugfix? :)

2024-05-10 07:21 UTC, sykhro commented on src/ui/qt/services/MenuManager.h
> +#include <sys/syslog.h>
Will break on windows (why is this even needed?)

2024-05-10 07:21 UTC, sykhro commented on src/ui/qt/services/MenuManager.h
> +              L_ERROR("Unknown PropertySpecValueType value: {}", static_cast<int>(propSpec.valueType));
just fyi, spdlog uses libfmt/std::format. with both of those, we can define custom formatters for our objects, so in cases like this you could have a nicer message than just a number. it goes really well when paired with [magic_enum](https://github.com/Neargye/magic_enum)

2024-05-10 08:35 UTC, mikelow commented on src/main/components/VGMColl.cpp
> +        sampInfo->SetPitchInfo(realUnityKey, realFineTune, attenuation);
Actually, no. This can just be called earlier in the function. Was part of trying to change the interface of AddSampInfo and other AddX functions in SynthFile to accept a reference or value of the type, rather than the weird behavior of instantiating an instance and returning it. 

Decided such a refactor would be better suited for a different PR.

2024-05-10 08:36 UTC, mikelow commented on src/main/conversion/SynthFile.h
> +        fusOptions(0), usPhaseGroup(0), channel(1), tableIndex(0), sampinfo(nullptr), art(nullptr) { }
Much cleaner. Will change

2024-05-10 08:46 UTC, mikelow commented on src/ui/qt/services/MenuManager.h
> +              L_ERROR("Unknown PropertySpecValueType value: {}", static_cast<int>(propSpec.valueType));
Ok, something I'll have to research. Do you think we should add magic_enum as a dependency? I actually bookmarked that project while researching stuff for LogManager (wanted to log the name of the calling class - no great solutions).

2024-05-10 09:12 UTC, sykhro commented on src/ui/qt/services/MenuManager.h
> +              L_ERROR("Unknown PropertySpecValueType value: {}", static_cast<int>(propSpec.valueType));
The closest thing to that in standard c++20 is `std::source_location` + `std::filesystem::path` to extract the filename of the calling code.
magic_enum might be useful, can't think of a specific usecase in this project though atm

2024-05-12 00:46 UTC, mikelow commented on src/ui/qt/services/MenuManager.h
> +              L_ERROR("Unknown PropertySpecValueType value: {}", static_cast<int>(propSpec.valueType));
Ah, I see. It sounds like this might present a better alternative to my current compromise solution, which is to use __FILE_NAME__ in compilers that support it. One of my goals was to exclude the full path from the compiled code.

I see now how one can define a fmt::formatter<SomeClass> struct to create a custom formatter. Seemsl ike overkill for PropertySpecValueType, though.

2024-05-20 05:22 UTC, mikelow commented
I believe the issues have been addressed. Let me know if this is good to go.

2024-05-20 07:12 UTC, sykhro approved these changes
LGTM! Sorry, didn't notice the push

2024-05-20 21:40 UTC, merged