Akao Format improvements
vgmtrans/vgmtrans pull request #526
Opened 2024-08-02 01:38 UTC by mikelow

This provides three improvements to the Akao format:

1. Adds support for creating collections that use more than one sample collection (Vagrant Story, FF8, others?)
2. Adds a new AkaoMatcher class that better handles the complicated task of determining what files belong in an Akao collection
3. Combines instrument region ADSR with articulation data ADSR, as opposed to only utilizing the articulation data ADSR. This fixes a lot of tracks with broken-sounding instruments.

## Description
Heads up that the Akao format itself is a complete mess. For the sake of matching, the relevant facts are:

1. Sequences and instrument sets are bundled together effectively as one file in their original format, so they are given the same id when we create them in the scanner.
2. Sequences contain a byte that indicates the id of an associated sample collection. However, a sequence may utilize a second common sample collection for which no id is provided. Final Fantasy VIII and Vagrant Story are examples of games that do this.
3. PSF sets sometimes exclude the aforementioned sample id association byte or the id byte of the sample collection itself. This is because removing all unread bytes is an optional feature of the PSF creation software, and these bytes are never actually read during playback.
4. Sample collections contain a list of "articulations." Each have an id, point to a sample, and provide ADSR data.
5. Each instrument region, defined in the instrument set, points to an articulation ID.

Therefore, we are limited in terms of guaranteed information. The goal is to ensure that the articulation IDs used in the regions of the instrument set are all present and accounted for, and there may be multiple sample collections that cover all the used articulation ids - so there is some unavoidable guessing. The implemented strategy is to utilize the associated sample collection if it is detected, but otherwise use any sample collection that covers any referenced articulation ids. 

However, we could get better results if the AkaoMatcher class had a callback informing it that a RawFile has finished loading.  Consider what happens when a PSF is loaded. A sequence may point to an associated sample collection ID, but we have no idea if the sample collection will have its id byte present. We also don't know when we have finished loading all the files of the PSF, so we must assume that each file is the last and check if it can be used in the collection. 

If instead the Matcher were informed when RawFile has finished loading, it could first evaluate if a sample collection with the correct ID was loaded. If not, it could check if the RawFile was a PSF, in which case it would make its best attempt to find the correct sample collection(s) exclusively from the files just loaded.

To solve this, I will creating another PR to provide the Scanner class with a pointer to its Format. This way, a Scanner can get the Format's Matcher instance and inform the Matcher when it has finished loading files.

## How Has This Been Tested?
I've tested this on a large number of Akao sets. In terms of matching results, it will sometimes perform better or worse compared to FilegroupMatcher, but the cons should be addressed in a future PR once we provide the Matcher with a new callback.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.

2024-08-02 11:44 UTC, sykhro commented on src/main/formats/Akao/AkaoFormat.cpp
> +    auto* instr = dynamic_cast<AkaoInstr*>(vgminstr);
this might be null if the `dynamic_cast` fails. probably impossible in this codepath but worth keeping in mind

2024-08-04 10:28 UTC, sykhro requested changes

2024-08-04 10:28 UTC, sykhro commented on src/main/formats/Akao/AkaoMatcher.cpp
> +        std::cout << "Collection created successfully!" << std::endl;
debug leftover?

2024-08-04 10:28 UTC, sykhro commented on src/main/formats/Akao/AkaoFormat.cpp
> +    auto regions = instr->regions();
is this copy intentional?

2024-08-04 10:28 UTC, sykhro commented on src/main/formats/Akao/AkaoFormat.h
> +  uint32_t numInstrsToAdd;
I would take the opportunity to move the initialization for `origInstrSet` and `numInstrsToAdd` here

2024-08-04 11:24 UTC, mikelow commented on src/main/formats/Akao/AkaoFormat.cpp
> +  std::map<int, AkaoSampColl*> artIdToSampCollMap;
Yes indeed.

2024-08-04 11:24 UTC, mikelow commented on src/main/formats/Akao/AkaoFormat.cpp
> +  return std::make_tuple(artIdToArtMap, artIdToSampleNumMap, artIdToSampCollMap);
Thank you!

2024-08-04 11:24 UTC, mikelow commented on src/main/formats/Akao/AkaoMatcher.cpp
> +        std::cout << "Collection created successfully!" << std::endl;
💯

2024-08-04 11:25 UTC, mikelow commented on src/main/formats/Akao/AkaoFormat.cpp
> +    auto regions = instr->regions();
Nope. Must be some leftover from earlier logic. I've removed it.

2024-08-04 11:25 UTC, mikelow commented on src/main/formats/Akao/AkaoFormat.h
> +  uint32_t numInstrsToAdd;
Done and done.

2024-08-04 12:31 UTC, sykhro approved these changes

2024-08-04 19:28 UTC, merged